# Generated by Django 4.1 on 2022-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=25)),
                ('bidang_usaha', models.TextField()),
                ('deskripsi_usaha', models.TextField()),
                ('kontak_usaha', models.EmailField(max_length=254)),
                ('lokasi_usaha', models.CharField(max_length=50)),
                ('website_usaha', models.URLField(default='https://www.google.com/search?q=<django.db.models.fields.CharField>')),
            ],
        ),
    ]
