# Generated by Django 4.1 on 2022-10-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='website_usaha',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
