# Generated by Django 4.1 on 2022-10-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm_module', '0002_alter_umkm_website_usaha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umkm',
            old_name='kontak_usaha',
            new_name='email_usaha',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='bidang_usaha',
        ),
        migrations.AddField(
            model_name='umkm',
            name='bidang_agribisnis',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umkm',
            name='bidang_fashion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umkm',
            name='bidang_kuliner',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umkm',
            name='image',
            field=models.ImageField(default='/media/image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
