# Generated by Django 4.1 on 2022-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm_module', '0004_rename_image_umkm_logo_usaha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='bidang_agribisnis',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='bidang_fashion',
        ),
        migrations.RemoveField(
            model_name='umkm',
            name='bidang_kuliner',
        ),
        migrations.AddField(
            model_name='umkm',
            name='bidang_usaha',
            field=models.CharField(default='Kuliner', max_length=25),
            preserve_default=False,
        ),
    ]
