# Generated by Django 4.1 on 2022-10-29 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umkm_module', '0005_remove_umkm_bidang_agribisnis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='pemilik_usaha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
