# Generated by Django 4.1 on 2022-12-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm_module', '0006_umkm_pemilik_usaha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='logo_usaha',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png'),
        ),
    ]
