# Generated by Django 4.1 on 2022-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm_module', '0007_alter_umkm_logo_usaha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='pemilik_usaha',
            field=models.CharField(max_length=25),
        ),
    ]
