# Generated by Django 4.1 on 2022-10-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="KritikPost", new_name="Post",),
    ]
