# Generated by Django 4.1 on 2022-10-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0006_post_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="user",),
    ]
