# Generated by Django 4.1 on 2022-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0008_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="username",
            field=models.CharField(default="Anonymous", max_length=200),
        ),
    ]
