# Generated by Django 4.1 on 2022-10-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0009_post_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="likes", field=models.IntegerField(default=0),
        ),
    ]
