# Generated by Django 4.1 on 2022-10-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0016_post_liked_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="username", field=models.CharField(max_length=200),
        ),
    ]
