# Generated by Django 4.1 on 2022-10-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0017_alter_post_username"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="liked", new_name="likes",),
    ]
