# Generated by Django 4.1 on 2022-10-31 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kritiksaran_module", "0020_post_date_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="setuju",
            field=models.ManyToManyField(
                blank=True, related_name="setuju", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Setuju",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="kritiksaran_module.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setujuer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
