# Generated by Django 4.1 on 2022-10-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0021_post_setuju_setuju"),
    ]

    operations = [
        migrations.DeleteModel(name="Like",),
    ]
