# Generated by Django 4.1 on 2022-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0023_remove_post_date_made_post_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="contact", field=models.IntegerField(null=True),
        ),
    ]
