# Generated by Django 4.1 on 2022-10-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kritiksaran_module", "0024_alter_post_contact"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="contact",),
    ]
