# Generated by Django 4.1 on 2022-11-02 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kritiksaran_module', '0026_remove_post_liked_alter_post_setuju'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kritik_saran', to=settings.AUTH_USER_MODEL),
        ),
    ]
